---
all:
  children:
    pod-gear:
      children:
        pod-routers:
          hosts:
            R1:
              ansible_host: 192.168.122.101
            R2:
              ansible_host: 192.168.122.102
            R3:
              ansible_host: 192.168.122.105
            R4:
              ansible_host: 192.168.122.106
        pod-switches:
          hosts:
            SW1:
              ansible_host: 192.168.122.103
            SW2:
              ansible_host: 192.168.122.104
            SW3:
              ansible_host: 192.168.122.107
            SW4:
              ansible_host: 192.168.122.108
    infra:
      children:
        matrix-switches:
          hosts:
            matrix-1:
              ansible_host: 192.168.122.151
            matrix-2:
              ansible_host: 192.168.122.152
            matrix-3:
              ansible_host: 192.168.122.153
            matrix-4:
              ansible_host: 192.168.122.154
