---
- name: Collect facts
  hosts: cisco
  vars:
    creds:
      host: "{{ host }}"
      username: "{{ username }}"
      password: "{{ password }}"
  tasks:
    ios_facts:
      provider: "{{ creds }}"